### ISSUE TITLE
oi

### ISSUE THREAD

**Issue by lucasbezerra26** [barretoMarcosPaulo/amigos-da-comunidade#2]

**Comment by lucasbezerra26** [comment]
@barretoMarcosPaulo 
@RuybProgramming 
@elievelton 
@thalianegomes

**Comment by lucasbezerra26** [comment]
me sigam

**Comment by lucasbezerra26** [comment]
@thalianegomes é falsa

**Comment by thalianegomes** [comment]
kkkkk tem o que fazer não Bezerra?

Em ter, 29 de out de 2019 às 15:12, lucasbezerra26 <notifications@github.com>
escreveu:
